GET http://localhost:3028/getAuthors


####


POST http://localhost:3028/createAuthor
Content-Type: application/json

{
    "name": "Luca",
    "surname": "Maggi",
    "email": "emailAndrea@email.it",
    "password": "prova",
    "birthday": "15/07/1995",
    "avatar": "https://tse1.mm.bing.net/th?id=OIP.awAiMS1BCAQ2xS2lcdXGlwHaHH&pid=Api&rs=1&c=1&qlt=95&w=116&h=111"
}

####

GET http://localhost:3028/getAuthor/65f32cfe367f72ef8b11d98e

####

PATCH http://localhost:3028/updateAuthor/65f32cfe367f72ef8b11d98e
Content-Type: application/json

{
    "surname": "Pasc"
}

####

DELETE http://localhost:3028/deleteAuthor/65f320a920074f7b8b790b9f

####


#  !CHIAMATE POST

GET http://localhost:3028/getPosts

####

POST http://localhost:3028/createPost
Content-Type: application/json

{
    "category": "Photography",
    "title": "500px",
    "cover": "https://wpblog.zyro.com/cdn-cgi/image/w=700,q=85/wp-content/uploads/2020/10/fotografia-di-ritratto.png",
    "readTime": 22,
    "author": { "name" : "...",
                 "avatar": "https://tse1.mm.bing.net/th?id=OIP.awAiMS1BCAQ2xS2lcdXGlwHaHH&pid=Api&rs=1&c=1&qlt=95&w=125&h=120"},
    "content": "https://iso.500px.com/",
    "comments": "66043c72ea6a00769c409cb0"
}

####

GET http://localhost:3028/getPost/6605808c69da0bc0a9baff3e

####


PATCH http://localhost:3028/updatePost/65f46681e7a127c70002701d
Content-Type: application/json

{
    "title" : "Moon"
}

####

DELETE http://localhost:3028/deletePost/65f466abe7a127c700027021

####

# !LOGIN TEST

POST http://localhost:3028/login
Content-Type: application/json

{
    "email": "emailMatteo@email.it",
    "password": "prova"
}

####

# !MODIFICA AVATAR AUTHOR

PATCH http://localhost:3028/authors/65faee2aeb3c006d10f3a312/avatar
Content-Type: application/json

{
    "avatar": "https://tse2.mm.bing.net/th?id=OIP.rM0tzYnXYqmdR5G6LtAdRgHaHa&pid=Api&P=0&h=180"
}

####

# !MODIFICA COVER POST

PATCH http://localhost:3028/posts/65fd8f217417a944f32a0392/cover 
Content-Type: application/json

{
    "cover": "https://tse1.mm.bing.net/th?id=OIP.vY1lY79ihHx3VblO3czu1wHaDt&pid=Api&rs=1&c=1&qlt=95&w=231&h=115"
}

####

# !TEST COMMENTS

GET http://localhost:3028/blogPosts/6605808c69da0bc0a9baff3e/comments

####

POST http://localhost:3028/blogPosts/66066e1f0d68eaa728337736
Content-Type: application/json

{
    "user": "User n°1",
    "comment": "Commento di Prova",
    "date": "Date: 29/03/2024"
}

####

PATCH http://localhost:3028/blogPosts/66059f578620b7e281f63a3d/comments/6605a14de2b5ec6c40f3aea3
Content-Type: application/json

{
    "user": "Secondo user di prova"
}

####

DELETE http://localhost:3028/blogPosts/66066e1f0d68eaa728337736/deleteComment/66066e340d68eaa72833773f